# Generated by Django 4.1 on 2025-01-05 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_alter_article_pronunciation_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_be', models.TextField(verbose_name='Змест на беларускай')),
                ('body_zh', models.TextField(verbose_name='Змест на кітайскай')),
            ],
            options={
                'verbose_name': 'Прыклад',
                'verbose_name_plural': 'Прыклады',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Артыкул', 'verbose_name_plural': 'Артыкулы'},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(verbose_name='Змест'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pronunciation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вымаўленне'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Загаловак'),
        ),
    ]
