# Generated by Django 5.1.1 on 2024-09-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_alter_article_pinyin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="description",
            new_name="body",
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
