# Generated by Django 5.1.1 on 2024-09-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_rename_description_article_body_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="translation_direction",
            field=models.TextField(
                choices=[("BK", "Bel To Cn"), ("KB", "Cn To Bel")],
                default="KB",
                max_length=2,
            ),
        ),
    ]
