# Generated by Django 4.2 on 2025-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_article_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='direction',
            field=models.CharField(choices=[('BC', 'Бел-кіт'), ('CB', 'Кіт-бел')], default='BC', max_length=2, verbose_name='Напрамак перакладу'),
        ),
    ]
